const $=id=>document.getElementById(id),SCAN_KEY='manko_catalog_scan';
function show(s){$('status').textContent=JSON.stringify({running:s.running,current:s.current,queued:s.queue?.length||0,results:s.results?.length||0,errors:s.errors?.length||0,lastResult:s.results?.at(-1)||null,lastError:s.errors?.at(-1)||null},null,2)}
async function refresh(){const s=await chrome.runtime.sendMessage({type:'GET_STATE'});show(s);const scan=(await chrome.storage.local.get(SCAN_KEY))[SCAN_KEY];if(scan)$('scanInfo').textContent=`Catalog scan: ${scan.count} unique movie URL(s) from ${scan.pageUrl}`;return s}
$('start').onclick=async()=>{const urls=$('urls').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const r=await chrome.runtime.sendMessage({type:'START_QUEUE',urls});$('scanInfo').textContent=`Added ${r.added} URL(s)`;setTimeout(refresh,500)};
$('scanManko').onclick=async()=>{const tabs=await chrome.tabs.query({active:true,currentWindow:true}),tab=tabs[0];if(!tab?.id||!String(tab.url||'').startsWith('https://manko.fun/'))return $('scanInfo').textContent='Open a Manko catalog/list page first.';try{const r=await chrome.tabs.sendMessage(tab.id,{type:'SCAN_MANKO_CATALOG'});const urls=[...new Set(r.urls||[])],scan={pageUrl:r.pageUrl,count:urls.length,urls,scannedAt:new Date().toISOString()};await chrome.storage.local.set({[SCAN_KEY]:scan});await chrome.runtime.sendMessage({type:'SYNC_CATALOG',pageUrl:r.pageUrl,urls});$('scanInfo').textContent=`Found ${urls.length} movie URL(s).`}catch(e){$('scanInfo').textContent=`Scan error: ${e.message||e}`}};
$('test10').onclick=async()=>{const scan=(await chrome.storage.local.get(SCAN_KEY))[SCAN_KEY];if(!scan?.urls?.length)return $('scanInfo').textContent='Scan a Manko catalog first.';const s=await chrome.runtime.sendMessage({type:'GET_STATE'}),done=new Set((s.results||[]).map(x=>x.movieUrl)),failed=new Set((s.errors||[]).map(x=>x.movieUrl)),batch=scan.urls.filter(u=>!done.has(u)&&!failed.has(u)).slice(0,10);const r=await chrome.runtime.sendMessage({type:'START_QUEUE',urls:batch});$('scanInfo').textContent=`Batch test started: ${r.added} movie(s).`;setTimeout(refresh,500)};
$('backfill').onclick=async()=>{try{const r=await chrome.runtime.sendMessage({type:'BACKFILL_RESULTS'});if(!r?.ok){$('scanInfo').textContent=`Backfill failed: ${r?.error||'unknown error'}`;return}$('scanInfo').textContent=`Backfill started for ${r.queued} existing movie(s) from ${r.source}.`;setTimeout(refresh,500)}catch(e){$('scanInfo').textContent=`Backfill failed: ${e.message||e}`}};
$('syncAll').onclick=async()=>{const r=await chrome.runtime.sendMessage({type:'SYNC_ALL'});$('scanInfo').textContent=r?.ok?`Sync complete: ${r.resultsSynced}/${r.resultsTotal}`:`Sync issue: ${r?.lastError||'unknown'}`;setTimeout(refresh,500)};
$('refresh').onclick=refresh;$('clear').onclick=async()=>{await chrome.runtime.sendMessage({type:'CLEAR_RESULTS'});refresh()};$('export').onclick=async()=>{const s=await chrome.runtime.sendMessage({type:'GET_STATE'}),blob=new Blob([JSON.stringify({results:s.results||[],errors:s.errors||[]},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);chrome.downloads.download({url,filename:`manko-streams-${Date.now()}.json`,saveAs:true});setTimeout(()=>URL.revokeObjectURL(url),30000)};refresh();setInterval(refresh,2000);
