const STATE_KEY='manko_collector_state';
const API='https://manko-api.onrender.com';
const HEAL='https://healertanker.com';
const REFERER='https://javplayer.cc/';
const WORKERS=3;
const MAX_RETRIES=3;

async function getState(){const r=await chrome.storage.local.get(STATE_KEY);return r[STATE_KEY]||{queue:[],workers:{},retryCounts:{},errors:[],results:[],crawl:null,totalDiscovered:0,successCount:0}}
async function setState(s){await chrome.storage.local.set({[STATE_KEY]:s})}
function isManko(u=''){return /^https:\/\/manko\.fun\/movie-info\//.test(String(u))}
async function postJson(path,body){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let data=null;try{data=JSON.parse(t)}catch{}return{ok:r.ok,status:r.status,data,text:t.slice(0,300)}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function getJson(url){try{const r=await fetch(url,{cache:'no-store',credentials:'include'});if(!r.ok)return null;return await r.json()}catch{return null}}
const normKey=k=>String(k||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function pickDeep(obj,names){const wanted=new Set(names.map(normKey));let found='';function walk(v){if(found||v==null)return;if(Array.isArray(v)){for(const x of v)walk(x);return}if(typeof v==='object'){for(const [k,val] of Object.entries(v)){if(wanted.has(normKey(k))&&(typeof val==='string'||typeof val==='number')){found=String(val);return}walk(val)}}}walk(obj);return found}
async function translateVi(text){text=String(text||'').trim();if(!text)return'';if(/^[A-Z0-9_-]{2,20}$/.test(text))return text;try{const u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=vi&dt=t&q='+encodeURIComponent(text.slice(0,4500));const r=await fetch(u);if(!r.ok)return text;const j=await r.json();return(j?.[0]||[]).map(x=>x?.[0]||'').join('').trim()||text}catch{return text}}
function countryVi(v){return({japan:'Nhật Bản',japanese:'Nhật Bản',korea:'Hàn Quốc',china:'Trung Quốc',taiwan:'Đài Loan'})[String(v||'').trim().toLowerCase()]||v}
function languageVi(v){return({japanese:'Tiếng Nhật',english:'Tiếng Anh',korean:'Tiếng Hàn',chinese:'Tiếng Trung'})[String(v||'').trim().toLowerCase()]||v}
function cleanTitle(t){return String(t||'').replace(/\s*-\s*Watch Free in HD\s*\|\s*Manko\s*$/i,'').trim()}
async function enrichManko(movieId,pageTitle,pageMeta){const d=await getJson(`${HEAL}/swx/movie/detail/${encodeURIComponent(movieId)}`);const originalTitle=pickDeep(d,['title','name','movieTitle','englishTitle'])||cleanTitle(pageTitle);const description=pickDeep(d,['description','overview','synopsis','plot','summary'])||pageMeta.description||'';const releaseDate=pageMeta.releaseDate||pickDeep(d,['releaseDate','released','release','date','publishDate'])||'';const year=(releaseDate.match(/\b(19|20)\d{2}\b/)||[])[0]||pickDeep(d,['year','releaseYear'])||'';const runtime=pageMeta.runtime||pickDeep(d,['runtime','duration','length','movieLength'])||'';const studio=pageMeta.studio||pickDeep(d,['studio','maker','label','publisher'])||'';const rating=pageMeta.rating||pickDeep(d,['rating','score'])||'';const size=pageMeta.size||pickDeep(d,['size','fileSize'])||'';const actors=(pageMeta.actors||[]).filter(Boolean);const country=pageMeta.country||'Japan',language=pageMeta.language||'Japanese';const [titleVi,descriptionVi]=await Promise.all([translateVi(originalTitle),translateVi(description)]);return{originalTitle,titleVi,description,descriptionVi,actors,code:pageMeta.code||cleanTitle(pageTitle),rating,runtime,size,year,releaseDate,studio,country,countryVi:countryVi(country),language,languageVi:languageVi(language)}}

async function serverDoneSet(){const done=new Set();let skip=0,total=1;while(skip<total){const j=await getJson(`${API}/collector/results?skip=${skip}&limit=500`);if(!j)break;for(const x of j.items||[])if(x.movieUrl)done.add(x.movieUrl);total=Number(j.total||0);skip+=500;if(skip>50000)break}return done}
function workerAlarm(id){return `manko_worker_${id}`}
async function armWorker(id,seconds){await chrome.alarms.clear(workerAlarm(id));chrome.alarms.create(workerAlarm(id),{delayInMinutes:Math.max(0.1,seconds/60)})}
async function closeTabs(w){for(const id of [w?.movieTabId,w?.playerTabId])if(id)try{await chrome.tabs.remove(id)}catch{}}
function activeUrls(s){return new Set(Object.values(s.workers||{}).filter(Boolean).map(w=>w.movieUrl))}

async function pumpWorkers(){const s=await getState();s.workers=s.workers||{};const active=activeUrls(s);let changed=false;for(let id=0;id<WORKERS;id++){if(s.workers[id])continue;while(s.queue.length){const u=s.queue.shift();if(!isManko(u)||active.has(u))continue;const w={id,movieUrl:u,movieId:null,movieTabId:null,playerTabId:null,title:'',titleVi:'',poster:'',metadata:{},stream:null,startedAt:new Date().toISOString()};s.workers[id]=w;active.add(u);changed=true;break}}if(changed)await setState(s);for(let id=0;id<WORKERS;id++){const w=(await getState()).workers?.[id];if(w&&!w.movieTabId&&!w.playerTabId){try{const t=await chrome.tabs.create({url:w.movieUrl,active:false});const s2=await getState();if(s2.workers?.[id]){s2.workers[id].movieTabId=t.id;await setState(s2);await armWorker(id,35)}}catch(e){await failWorker(id,'open movie failed: '+String(e))}}}}

async function finishWorker(id,streamMsg){const s=await getState(),w=s.workers?.[id];if(!w)return;await chrome.alarms.clear(workerAlarm(id));if(streamMsg?.ok&&streamMsg.streamUrl){w.stream={name:'#1',url:streamMsg.streamUrl,headers:streamMsg.headers||{Referer:REFERER},playerId:streamMsg.playerId,playerUrl:streamMsg.playerUrl};const record={...w,streams:[w.stream],streamUrl:w.stream.url,headers:w.stream.headers,collectedAt:new Date().toISOString()};delete record.id;delete record.movieTabId;delete record.playerTabId;delete record.stream;const sync=await postJson('/collector/result',record);if(sync.ok){s.successCount=(s.successCount||0)+1;s.results=[...(s.results||[]).filter(x=>x.movieUrl!==w.movieUrl),{movieUrl:w.movieUrl,titleVi:w.titleVi,at:new Date().toISOString()}];s.retryCounts[w.movieUrl]=0;if(s.crawl&&!s.crawl.serverDone.includes(w.movieUrl))s.crawl.serverDone.push(w.movieUrl);await closeTabs(w);s.workers[id]=null;await setState(s);return pumpWorkers()}}
 return failWorker(id,streamMsg?.error||'stream/server failed')}

async function failWorker(id,reason){const s=await getState(),w=s.workers?.[id];if(!w)return;await chrome.alarms.clear(workerAlarm(id));await closeTabs(w);const n=(s.retryCounts[w.movieUrl]||0)+1;s.retryCounts[w.movieUrl]=n;s.workers[id]=null;if(n<MAX_RETRIES){s.queue.push(w.movieUrl)}else{s.errors=[...(s.errors||[]).filter(x=>x.movieUrl!==w.movieUrl),{movieUrl:w.movieUrl,error:reason,retries:n,at:new Date().toISOString()}]}await setState(s);pumpWorkers()}

function isListPage(u){try{const U=new URL(u);if(U.origin!=='https://manko.fun')return false;return U.pathname==='/home'||U.pathname.includes('movie-list')||U.pathname.includes('cate-list')}catch{return false}}
async function scrapeCatalog(tabId){const r=await chrome.scripting.executeScript({target:{tabId},func:async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const norm=h=>{try{return new URL(h,location.href).href}catch{return null}};const movies=()=>{const out=[],seen=new Set();for(const a of document.querySelectorAll('a[href]')){const u=norm(a.href||a.getAttribute('href'));if(u&&u.startsWith('https://manko.fun/movie-info/')&&!seen.has(u)){seen.add(u);out.push(u)}}return out};let stable=0,last=0;for(let i=0;i<10&&stable<2;i++){window.scrollTo(0,document.body.scrollHeight);await wait(250);const n=movies().length;if(n===last)stable++;else stable=0;last=n}const pages=[],seenPages=new Set();for(const a of document.querySelectorAll('a[href]')){const u=norm(a.href||a.getAttribute('href'));if(!u||seenPages.has(u))continue;try{const U=new URL(u);if(U.origin!=='https://manko.fun')continue;if(U.pathname==='/home'||U.pathname.includes('movie-list')||U.pathname.includes('cate-list')){seenPages.add(u);pages.push(u)}}catch{}}window.scrollTo(0,0);return{url:location.href,movies:movies(),pages}}});return r?.[0]?.result||{url:'',movies:[],pages:[]}}
async function syncCatalogOrder(s){const c=s.crawl;if(c)await postJson('/collector/catalog',{pageUrl:c.startUrl,urls:c.orderedUrls})}
async function enqueueMovies(s,urls){const doneSet=new Set(s.crawl?.serverDone||[]),busy=activeUrls(s),queued=new Set(s.queue||[]);for(const u of urls)if(!doneSet.has(u)&&!busy.has(u)&&!queued.has(u)){s.queue.push(u);queued.add(u)}}
async function gotoNextPage(){const s=await getState(),c=s.crawl;if(!c?.active)return;while(c.pagesPending.length&&c.pagesVisited.includes(c.pagesPending[0]))c.pagesPending.shift();if(!c.pagesPending.length){c.active=false;c.finishedAt=new Date().toISOString();await setState(s);await syncCatalogOrder(s);if(c.tabId)try{await chrome.tabs.remove(c.tabId)}catch{}pumpWorkers();return}const u=c.pagesPending.shift();c.currentPage=u;c.processing=false;await setState(s);try{if(c.tabId)await chrome.tabs.update(c.tabId,{url:u,active:false});else{const t=await chrome.tabs.create({url:u,active:false});c.tabId=t.id;await setState(s)}}catch(e){c.lastError=String(e);await setState(s);setTimeout(gotoNextPage,300)}}
async function handleCrawlLoaded(tabId){const s=await getState(),c=s.crawl;if(!c?.active||c.tabId!==tabId||c.processing)return;c.processing=true;await setState(s);try{const p=await scrapeCatalog(tabId),cur=p.url||c.currentPage;if(!c.pagesVisited.includes(cur))c.pagesVisited.push(cur);for(const u of p.pages||[])if(isListPage(u)&&!c.pagesVisited.includes(u)&&!c.pagesPending.includes(u))c.pagesPending.push(u);const fresh=[];for(const u of p.movies||[])if(!c.orderedUrls.includes(u)){c.orderedUrls.push(u);fresh.push(u)}c.pagesScanned=c.pagesVisited.length;c.moviesFound=c.orderedUrls.length;s.totalDiscovered=c.orderedUrls.length;await enqueueMovies(s,fresh);c.processing=false;await setState(s);await syncCatalogOrder(s);pumpWorkers();gotoNextPage()}catch(e){c.lastError=String(e);c.processing=false;if(c.currentPage&&!c.pagesVisited.includes(c.currentPage))c.pagesVisited.push(c.currentPage);await setState(s);gotoNextPage()}}
async function startFullCrawl(){const s=await getState();if(s.crawl?.active)return{ok:false,error:'Crawler đang chạy'};const done=await serverDoneSet();s.queue=[];s.errors=[];s.retryCounts=s.retryCounts||{};s.workers={};s.crawl={active:true,startUrl:'https://manko.fun/home',pagesPending:['https://manko.fun/home'],pagesVisited:[],orderedUrls:[],serverDone:[...done],pagesScanned:0,moviesFound:0,currentPage:null,tabId:null,processing:false,startedAt:new Date().toISOString(),lastError:null};await setState(s);gotoNextPage();return{ok:true,alreadyStored:done.size,workers:WORKERS}}
async function recover(){const s=await getState();s.queue=s.queue||[];for(const w of Object.values(s.workers||{}))if(w?.movieUrl&&!s.queue.includes(w.movieUrl))s.queue.unshift(w.movieUrl);s.workers={};if(s.crawl?.active){s.crawl.tabId=null;s.crawl.processing=false;if(s.crawl.currentPage&&!s.crawl.pagesVisited.includes(s.crawl.currentPage))s.crawl.pagesPending.unshift(s.crawl.currentPage)}await setState(s);if(s.crawl?.active)gotoNextPage();pumpWorkers()}

chrome.tabs.onUpdated.addListener((tabId,change)=>{if(change.status==='complete')handleCrawlLoaded(tabId)});
chrome.tabs.onRemoved.addListener(async tabId=>{const s=await getState();if(s.crawl?.active&&s.crawl.tabId===tabId){s.crawl.tabId=null;s.crawl.processing=false;if(s.crawl.currentPage&&!s.crawl.pagesVisited.includes(s.crawl.currentPage))s.crawl.pagesPending.unshift(s.crawl.currentPage);await setState(s);gotoNextPage()}});
chrome.alarms.onAlarm.addListener(async a=>{if(!a.name.startsWith('manko_worker_'))return;const id=Number(a.name.split('_').pop());await failWorker(id,'timeout')});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{(async()=>{
 if(msg.type==='START_FULL_CRAWL'){sendResponse(await startFullCrawl());return}
 if(msg.type==='RETRY_ERRORS'){const s=await getState(),urls=[...new Set((s.errors||[]).map(x=>x.movieUrl).filter(isManko))];s.errors=[];for(const u of urls){s.retryCounts[u]=0;if(!s.queue.includes(u)&&!activeUrls(s).has(u))s.queue.push(u)}await setState(s);pumpWorkers();sendResponse({ok:true,added:urls.length});return}
 if(msg.type==='MANKO_PLAYER_FOUND'){const tabId=sender.tab?.id,s=await getState();const entry=Object.entries(s.workers||{}).find(([,w])=>w?.movieTabId===tabId);if(!entry)return;const id=Number(entry[0]),w=entry[1];w.movieId=msg.movieId||((msg.movieUrl.match(/\/movie-info\/([^/?#]+)/)||[])[1]||'');w.title=msg.title||'';w.poster=msg.poster||'';w.metadata=await enrichManko(w.movieId,msg.title,msg.metadata||{});w.titleVi=w.metadata.titleVi||cleanTitle(msg.title);const first=msg.playerUrl||(msg.playerUrls||[])[0]||'';if(!first){sendResponse({ok:false});return failWorker(id,'No javplayer embed')}try{const t=await chrome.tabs.create({url:first,active:false});w.playerTabId=t.id;w.playerUrl=first;s.workers[id]=w;await setState(s);await armWorker(id,25);sendResponse({ok:true,worker:id})}catch(e){sendResponse({ok:false});failWorker(id,'open player failed: '+String(e))}return}
 if(msg.type==='JAVPLAYER_RESULT'){const tabId=sender.tab?.id,s=await getState();const entry=Object.entries(s.workers||{}).find(([,w])=>w?.playerTabId===tabId);if(!entry)return;const id=Number(entry[0]);sendResponse({ok:true,worker:id});if(msg.ok&&msg.streamUrl)return finishWorker(id,msg);return failWorker(id,'First stream failed')}
 if(msg.type==='GET_STATE'){sendResponse(await getState());return}
 })();return true});
chrome.runtime.onInstalled.addListener(recover);chrome.runtime.onStartup.addListener(recover);recover();
