const STATE_KEY='manko_collector_state';
const API='https://manko-api.onrender.com';
const HEAL='https://healertanker.com';
const REFERER='https://javplayer.cc/';
async function getState(){const r=await chrome.storage.local.get(STATE_KEY);return r[STATE_KEY]||{queue:[],running:false,current:null,results:[],errors:[],totalDiscovered:0,mode:'stream',metaDone:0,crawl:null}}
async function setState(s){await chrome.storage.local.set({[STATE_KEY]:s})}
function isManko(u=''){return u.startsWith('https://manko.fun/movie-info/')}
async function postJson(path,body){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let data=null;try{data=JSON.parse(t)}catch{}return{ok:r.ok,status:r.status,text:t.slice(0,300),data}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function getJson(url){try{const r=await fetch(url,{credentials:'include',cache:'no-store'});if(!r.ok)return null;return await r.json()}catch{return null}}
const normKey=k=>String(k||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function pickDeep(obj,names){const wanted=new Set(names.map(normKey));let found;function walk(v){if(found!==undefined||v==null)return;if(Array.isArray(v)){for(const x of v)walk(x);return}if(typeof v==='object'){for(const [k,val] of Object.entries(v)){if(wanted.has(normKey(k))&&(typeof val==='string'||typeof val==='number')){found=String(val);return}walk(val)}}}walk(obj);return found||''}
async function translateVi(text){text=String(text||'').trim();if(!text)return'';if(/^[A-Z0-9_-]{2,20}$/.test(text))return text;try{const u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=vi&dt=t&q='+encodeURIComponent(text.slice(0,4500));const r=await fetch(u);if(!r.ok)return text;const j=await r.json();return (j?.[0]||[]).map(x=>x?.[0]||'').join('').trim()||text}catch{return text}}
function countryVi(v){return ({japan:'Nhật Bản',japanese:'Nhật Bản',korea:'Hàn Quốc',china:'Trung Quốc',taiwan:'Đài Loan'})[String(v||'').trim().toLowerCase()]||v}
function languageVi(v){return ({japanese:'Tiếng Nhật',english:'Tiếng Anh',korean:'Tiếng Hàn',chinese:'Tiếng Trung'})[String(v||'').trim().toLowerCase()]||v}
function cleanPageTitle(t){return String(t||'').replace(/\s*-\s*Watch Free in HD\s*\|\s*Manko\s*$/i,'').trim()}
async function enrichManko(movieId,pageTitle,pageMeta){const detail=await getJson(`${HEAL}/swx/movie/detail/${encodeURIComponent(movieId)}`);const originalTitle=pickDeep(detail,['title','name','movieTitle','englishTitle'])||cleanPageTitle(pageTitle);const description=pickDeep(detail,['description','overview','synopsis','plot','summary'])||pageMeta.description||'';const releaseDate=pageMeta.releaseDate||pickDeep(detail,['releaseDate','released','release','date','publishDate'])||'';const year=(releaseDate.match(/\b(19|20)\d{2}\b/)||[])[0]||pickDeep(detail,['year','releaseYear'])||'';const runtime=pageMeta.runtime||pickDeep(detail,['runtime','duration','length','movieLength'])||'';const studio=pageMeta.studio||pickDeep(detail,['studio','maker','label','publisher'])||'';const actors=(pageMeta.actors||[]).filter(Boolean);const code=pageMeta.code||cleanPageTitle(pageTitle);const rating=pageMeta.rating||pickDeep(detail,['rating','score'])||'';const size=pageMeta.size||pickDeep(detail,['size','fileSize'])||'';const country=pageMeta.country||'Japan',language=pageMeta.language||'Japanese';const [titleVi,descriptionVi]=await Promise.all([translateVi(originalTitle),translateVi(description)]);return {originalTitle,titleVi,description,descriptionVi,actors,code,rating,runtime,size,year,releaseDate,studio,country,countryVi:countryVi(country),language,languageVi:languageVi(language),rawAvailable:{detail:!!detail}}}
async function processNext(){const s=await getState();if(s.running||!s.queue.length)return;const movieUrl=s.queue.shift();if(!isManko(movieUrl)){await setState(s);return processNext()}s.running=true;s.current={source:'manko',movieUrl,movieTabId:null,playerTabId:null,title:null,titleVi:null,poster:null,movieId:null,playerUrls:[],playerIndex:0,streams:[],metadata:{},mode:s.mode||'stream'};await setState(s);try{const tab=await chrome.tabs.create({url:movieUrl,active:false});s.current.movieTabId=tab.id;await setState(s)}catch(e){await finishCurrent(false,{error:String(e?.message||e)})}}
async function finishCurrent(ok,payload={}){const s=await getState(),cur=s.current||{},record={...cur,...payload,collectedAt:new Date().toISOString()};delete record.movieTabId;delete record.playerTabId;if(ok&&record.streams?.length){record.streamUrl=record.streams[0].url;record.headers=record.streams[0].headers||{Referer:REFERER};record.sync=await postJson('/collector/result',record);s.results=(s.results||[]).filter(x=>x.movieUrl!==record.movieUrl);s.results.push(record)}else if(!ok){s.errors=(s.errors||[]).filter(x=>x.movieUrl!==record.movieUrl);s.errors.push(record)}for(const id of [cur.movieTabId,cur.playerTabId])if(id)try{await chrome.tabs.remove(id)}catch{}s.running=false;s.current=null;await setState(s);processNext()}
async function finishMetadata(cur,metadata,title,titleVi,poster){const sync=await postJson('/collector/metadata',{movieUrl:cur.movieUrl,title,titleVi,poster,metadata});const s=await getState();if(sync.ok)s.metaDone=(s.metaDone||0)+1;else s.errors=[...(s.errors||[]),{movieUrl:cur.movieUrl,error:'metadata update failed',sync}];for(const id of [cur.movieTabId,cur.playerTabId])if(id)try{await chrome.tabs.remove(id)}catch{}s.running=false;s.current=null;await setState(s);processNext()}
async function openNextPlayer(){const s=await getState(),c=s.current;if(!c)return;if(c.playerTabId)try{await chrome.tabs.remove(c.playerTabId)}catch{}c.playerTabId=null;if(c.playerIndex>=c.playerUrls.length){await setState(s);return finishCurrent(c.streams.length>0)}const u=c.playerUrls[c.playerIndex++];try{const tab=await chrome.tabs.create({url:u,active:false});c.playerTabId=tab.id;await setState(s)}catch{await setState(s);return openNextPlayer()}}

async function movieYear(url){const id=(String(url).match(/\/movie-info\/([^/?#]+)/)||[])[1];if(!id)return'';const d=await getJson(`${HEAL}/swx/movie/detail/${encodeURIComponent(id)}`);if(!d)return'';const rd=pickDeep(d,['releaseDate','released','release','date','publishDate']);return String(pickDeep(d,['year','releaseYear'])||(rd.match(/\b(19|20)\d{2}\b/)||[])[0]||'')}
async function mapLimit(items,limit,fn){const out=[];let i=0;async function worker(){while(i<items.length){const n=i++;try{out[n]=await fn(items[n])}catch{out[n]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function scrapeCatalog(tabId){const r=await chrome.scripting.executeScript({target:{tabId},func:async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms));const norm=href=>{try{const u=new URL(href,location.href);return u.origin==='https://manko.fun'?u.href:null}catch{return null}};const collectMovies=()=>[...new Set([...document.querySelectorAll('a[href]')].map(a=>norm(a.href||a.getAttribute('href'))).filter(u=>u&&u.includes('/movie-info/')))];let stable=0,last=collectMovies().length;for(let n=0;n<30&&stable<5;n++){window.scrollTo({top:document.body.scrollHeight,behavior:'instant'});for(const el of [...document.querySelectorAll('button,a,[role="button"]')]){const t=(el.textContent||'').trim().toLowerCase();if(/load more|show more|xem thêm/.test(t)){try{el.click()}catch{}}}await sleep(800);const c=collectMovies().length;if(c===last)stable++;else stable=0;last=c}const movies=collectMovies();const pages=new Set();for(const a of document.querySelectorAll('a[href]')){const u=norm(a.href||a.getAttribute('href'));if(!u||u.includes('/movie-info/'))continue;const rel=(a.getAttribute('rel')||'').toLowerCase(),txt=(a.textContent||'').trim().toLowerCase(),parent=(a.closest('nav,[class*="pagin"],[aria-label*="pagin"]')?1:0);if(rel.includes('next')||parent||/[?&]page=\d+/i.test(u)||/\/page\/\d+/i.test(u)||/^next$|^›$|^»$/.test(txt))pages.add(u)}window.scrollTo({top:0,behavior:'instant'});return{url:location.href,movies,pages:[...pages]}}});return r?.[0]?.result||{url:'',movies:[],pages:[]}}
async function gotoNextCrawlPage(){const s=await getState(),c=s.crawl;if(!c?.active)return;while(c.pagesPending.length&&c.pagesVisited.includes(c.pagesPending[0]))c.pagesPending.shift();if(!c.pagesPending.length){c.active=false;c.finishedAt=new Date().toISOString();const matched=[...new Set(c.matched||[])];const done=new Set((s.results||[]).map(x=>x.movieUrl));const busy=new Set([...(s.queue||[]),s.current?.movieUrl].filter(Boolean));for(const u of matched)if(!done.has(u)&&!busy.has(u))s.queue.push(u);s.mode='stream';s.totalDiscovered=matched.length;await setState(s);await postJson('/collector/catalog',{pageUrl:c.startUrl,urls:matched,year:c.targetYear});if(c.tabId)try{await chrome.tabs.remove(c.tabId)}catch{}processNext();return}
 const url=c.pagesPending.shift();c.currentPage=url;await setState(s);try{if(c.tabId){await chrome.tabs.update(c.tabId,{url,active:false})}else{const t=await chrome.tabs.create({url,active:false});c.tabId=t.id;await setState(s)}}catch(e){c.lastError=String(e?.message||e);await setState(s);setTimeout(gotoNextCrawlPage,1000)}}
async function handleCrawlLoaded(tabId){const s=await getState(),c=s.crawl;if(!c?.active||c.tabId!==tabId||c.processing)return;c.processing=true;await setState(s);try{const page=await scrapeCatalog(tabId);const cur=page.url||c.currentPage;if(!c.pagesVisited.includes(cur))c.pagesVisited.push(cur);for(const p of page.pages||[])if(!c.pagesVisited.includes(p)&&!c.pagesPending.includes(p))c.pagesPending.push(p);const newMovies=(page.movies||[]).filter(u=>!c.moviesSeen.includes(u));c.moviesSeen.push(...newMovies);const years=await mapLimit(newMovies,6,movieYear);for(let i=0;i<newMovies.length;i++){c.checked=(c.checked||0)+1;if(years[i]===String(c.targetYear)&&!c.matched.includes(newMovies[i]))c.matched.push(newMovies[i])}c.pagesScanned=c.pagesVisited.length;c.processing=false;await setState(s);await gotoNextCrawlPage()}catch(e){c.lastError=String(e?.message||e);c.processing=false;if(c.currentPage&&!c.pagesVisited.includes(c.currentPage))c.pagesVisited.push(c.currentPage);await setState(s);await gotoNextCrawlPage()}}
async function startYearCrawl(startUrl,year=2016){if(!String(startUrl||'').startsWith('https://manko.fun/'))return{ok:false,error:'Open a Manko catalog page first'};const s=await getState();if(s.crawl?.active)return{ok:false,error:'crawl already running'};s.queue=[];s.mode='stream';s.crawl={active:true,targetYear:Number(year),startUrl,pagesPending:[startUrl],pagesVisited:[],moviesSeen:[],matched:[],checked:0,pagesScanned:0,currentPage:null,tabId:null,processing:false,startedAt:new Date().toISOString(),lastError:null};await setState(s);await gotoNextCrawlPage();return{ok:true,year:Number(year)}}
async function recoverAndResume(){const s=await getState();if(s.running&&s.current?.movieUrl){if(!s.queue.includes(s.current.movieUrl))s.queue.unshift(s.current.movieUrl);s.running=false;s.current=null;await setState(s)}if(s.crawl?.active){s.crawl.processing=false;s.crawl.tabId=null;await setState(s);gotoNextCrawlPage()}processNext()}
async function startMetadataBackfill(){const s=await getState();if(s.running||s.queue.length)return{ok:false,error:'collector busy',queued:s.queue.length};const data=await getJson(`${API}/collector/results?skip=0&limit=500`);const urls=[...new Set((data?.items||[]).map(x=>x.movieUrl).filter(isManko))];if(!urls.length)return{ok:false,error:'no stored movies'};s.mode='metadata';s.queue=urls;s.metaDone=0;s.errors=[];await setState(s);processNext();return{ok:true,total:urls.length}}

chrome.tabs.onUpdated.addListener((tabId,change)=>{if(change.status==='complete')handleCrawlLoaded(tabId)});
chrome.tabs.onRemoved.addListener(async tabId=>{const s=await getState();if(s.crawl?.active&&s.crawl.tabId===tabId){s.crawl.tabId=null;s.crawl.processing=false;if(s.crawl.currentPage&&!s.crawl.pagesVisited.includes(s.crawl.currentPage))s.crawl.pagesPending.unshift(s.crawl.currentPage);await setState(s);gotoNextCrawlPage()}});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{(async()=>{
 if(msg.type==='START_YEAR_CRAWL'){sendResponse(await startYearCrawl(msg.startUrl,msg.year||2016));return}
 if(msg.type==='START_QUEUE'){const s=await getState();if(s.mode==='metadata'&&(s.running||s.queue.length)){sendResponse({ok:false,error:'metadata backfill running'});return}s.mode='stream';const done=new Set((s.results||[]).map(x=>x.movieUrl));const busy=new Set([...(s.queue||[]),s.current?.movieUrl].filter(Boolean));const incoming=[...new Set((msg.urls||[]).map(x=>String(x).trim()).filter(isManko))];const added=incoming.filter(u=>!done.has(u)&&!busy.has(u));s.queue.push(...added);s.totalDiscovered=Math.max(Number(s.totalDiscovered||0),incoming.length);await setState(s);processNext();sendResponse({ok:true,added:added.length,alreadyDone:incoming.length-added.length,total:incoming.length});return}
 if(msg.type==='START_METADATA_BACKFILL'){sendResponse(await startMetadataBackfill());return}
 if(msg.type==='SYNC_CATALOG'){sendResponse(await postJson('/collector/catalog',{pageUrl:msg.pageUrl,urls:msg.urls||[]}));return}
 if(msg.type==='RETRY_ERRORS'){const s=await getState();const retry=[...new Set((s.errors||[]).map(x=>x.movieUrl).filter(isManko))];s.errors=[];for(const u of retry)if(!s.queue.includes(u))s.queue.push(u);await setState(s);processNext();sendResponse({ok:true,added:retry.length});return}
 if(msg.type==='MANKO_PLAYER_FOUND'){const s=await getState();if(!s.current)return;const cur=s.current;cur.movieId=msg.movieId||((msg.movieUrl.match(/\/movie-info\/([^/?#]+)/)||[])[1]||'');cur.title=msg.title||'';cur.poster=msg.poster||'';cur.metadata=await enrichManko(cur.movieId,msg.title,msg.metadata||{});cur.titleVi=cur.metadata.titleVi||cleanPageTitle(msg.title);if((s.mode||cur.mode)==='metadata'){await setState(s);sendResponse({ok:true,metadataOnly:true});return finishMetadata(cur,cur.metadata,cur.title,cur.titleVi,cur.poster)}cur.playerUrls=[...new Set((msg.playerUrls||[msg.playerUrl]).filter(Boolean))];cur.playerIndex=0;cur.streams=[];await setState(s);if(!cur.playerUrls.length){sendResponse({ok:false});return finishCurrent(false,{error:'No javplayer embed'})}await openNextPlayer();sendResponse({ok:true,players:cur.playerUrls.length});return}
 if(msg.type==='JAVPLAYER_RESULT'){const s=await getState(),c=s.current;if(!c||s.mode==='metadata')return;if(msg.ok&&msg.streamUrl&&!c.streams.some(x=>x.url===msg.streamUrl))c.streams.push({name:'#'+(c.streams.length+1),url:msg.streamUrl,headers:msg.headers||{Referer:REFERER},playerId:msg.playerId,playerUrl:msg.playerUrl});await setState(s);await openNextPlayer();sendResponse({ok:true});return}
 if(msg.type==='GET_STATE'){sendResponse(await getState());return}
 })();return true});
chrome.runtime.onInstalled.addListener(()=>recoverAndResume());chrome.runtime.onStartup.addListener(()=>recoverAndResume());recoverAndResume();
