const STATE_KEY='manko_collector_state';
const API='https://manko-api.onrender.com';
const HEAL='https://healertanker.com';
const REFERER='https://javplayer.cc/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function getState(){const r=await chrome.storage.local.get(STATE_KEY);return r[STATE_KEY]||{queue:[],running:false,current:null,results:[],errors:[],mode:'stream',crawl:null,totalDiscovered:0}}
async function setState(s){await chrome.storage.local.set({[STATE_KEY]:s})}
function isManko(u=''){return /^https:\/\/manko\.fun\/movie-info\//.test(String(u))}
async function postJson(path,body){try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let data=null;try{data=JSON.parse(t)}catch{}return{ok:r.ok,status:r.status,data,text:t.slice(0,300)}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function getJson(url){try{const r=await fetch(url,{cache:'no-store',credentials:'include'});if(!r.ok)return null;return await r.json()}catch{return null}}
const normKey=k=>String(k||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function pickDeep(obj,names){const wanted=new Set(names.map(normKey));let found='';function walk(v){if(found||v==null)return;if(Array.isArray(v)){for(const x of v)walk(x);return}if(typeof v==='object'){for(const [k,val] of Object.entries(v)){if(wanted.has(normKey(k))&&(typeof val==='string'||typeof val==='number')){found=String(val);return}walk(val)}}}walk(obj);return found}
async function translateVi(text){text=String(text||'').trim();if(!text)return'';if(/^[A-Z0-9_-]{2,20}$/.test(text))return text;try{const u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=vi&dt=t&q='+encodeURIComponent(text.slice(0,4500));const r=await fetch(u);if(!r.ok)return text;const j=await r.json();return (j?.[0]||[]).map(x=>x?.[0]||'').join('').trim()||text}catch{return text}}
function countryVi(v){return({japan:'Nhật Bản',japanese:'Nhật Bản',korea:'Hàn Quốc',china:'Trung Quốc',taiwan:'Đài Loan'})[String(v||'').trim().toLowerCase()]||v}
function languageVi(v){return({japanese:'Tiếng Nhật',english:'Tiếng Anh',korean:'Tiếng Hàn',chinese:'Tiếng Trung'})[String(v||'').trim().toLowerCase()]||v}
function cleanTitle(t){return String(t||'').replace(/\s*-\s*Watch Free in HD\s*\|\s*Manko\s*$/i,'').trim()}
async function enrichManko(movieId,pageTitle,pageMeta){const d=await getJson(`${HEAL}/swx/movie/detail/${encodeURIComponent(movieId)}`);const originalTitle=pickDeep(d,['title','name','movieTitle','englishTitle'])||cleanTitle(pageTitle);const description=pickDeep(d,['description','overview','synopsis','plot','summary'])||pageMeta.description||'';const releaseDate=pageMeta.releaseDate||pickDeep(d,['releaseDate','released','release','date','publishDate'])||'';const year=(releaseDate.match(/\b(19|20)\d{2}\b/)||[])[0]||pickDeep(d,['year','releaseYear'])||'';const runtime=pageMeta.runtime||pickDeep(d,['runtime','duration','length','movieLength'])||'';const studio=pageMeta.studio||pickDeep(d,['studio','maker','label','publisher'])||'';const rating=pageMeta.rating||pickDeep(d,['rating','score'])||'';const size=pageMeta.size||pickDeep(d,['size','fileSize'])||'';const actors=(pageMeta.actors||[]).filter(Boolean);const country=pageMeta.country||'Japan',language=pageMeta.language||'Japanese';const [titleVi,descriptionVi]=await Promise.all([translateVi(originalTitle),translateVi(description)]);return{originalTitle,titleVi,description,descriptionVi,actors,code:pageMeta.code||cleanTitle(pageTitle),rating,runtime,size,year,releaseDate,studio,country,countryVi:countryVi(country),language,languageVi:languageVi(language)}}

async function serverDoneSet(){const done=new Set();let skip=0,total=1;while(skip<total){const j=await getJson(`${API}/collector/results?skip=${skip}&limit=500`);if(!j)break;for(const x of j.items||[])if(x.movieUrl)done.add(x.movieUrl);total=Number(j.total||0);skip+=500;if(skip>20000)break}return done}
async function processNext(){const s=await getState();if(s.running||!s.queue.length)return;const u=s.queue.shift();if(!isManko(u)){await setState(s);return processNext()}s.running=true;s.current={movieUrl:u,movieId:null,movieTabId:null,playerTabId:null,title:'',titleVi:'',poster:'',playerUrls:[],playerIndex:0,streams:[],metadata:{}};await setState(s);try{const t=await chrome.tabs.create({url:u,active:false});s.current.movieTabId=t.id;await setState(s)}catch(e){await finishCurrent(false,{error:String(e)})}}
async function finishCurrent(ok,payload={}){const s=await getState(),c=s.current||{},record={...c,...payload,collectedAt:new Date().toISOString()};delete record.movieTabId;delete record.playerTabId;if(ok&&record.streams?.length){record.streamUrl=record.streams[0].url;record.headers=record.streams[0].headers||{Referer:REFERER};const sync=await postJson('/collector/result',record);if(sync.ok)s.results=[...(s.results||[]).filter(x=>x.movieUrl!==record.movieUrl),record];else s.errors=[...(s.errors||[]),{movieUrl:record.movieUrl,error:'server sync failed',sync}]}else if(!ok)s.errors=[...(s.errors||[]),record];for(const id of [c.movieTabId,c.playerTabId])if(id)try{await chrome.tabs.remove(id)}catch{}s.running=false;s.current=null;await setState(s);processNext()}
async function openNextPlayer(){const s=await getState(),c=s.current;if(!c)return;if(c.playerTabId)try{await chrome.tabs.remove(c.playerTabId)}catch{}c.playerTabId=null;if(c.playerIndex>=c.playerUrls.length){await setState(s);return finishCurrent(c.streams.length>0)}try{const t=await chrome.tabs.create({url:c.playerUrls[c.playerIndex++],active:false});c.playerTabId=t.id;await setState(s)}catch{await setState(s);openNextPlayer()}}

function pageNo(u){try{return Number(new URL(u).searchParams.get('page')||1)||1}catch{return 1}}
function sameCatalog(a,b){try{const A=new URL(a),B=new URL(b);if(A.origin!==B.origin)return false;const ca=A.searchParams.get('category')||'',cb=B.searchParams.get('category')||'';return ca===cb&&(B.pathname.includes('list')||B.searchParams.has('page'))}catch{return false}}
async function scrapeCatalog(tabId,startUrl){const r=await chrome.scripting.executeScript({target:{tabId},args:[startUrl],func:async(startUrl)=>{const wait=ms=>new Promise(r=>setTimeout(r,ms));const norm=h=>{try{return new URL(h,location.href).href}catch{return null}};const collect=()=>{const out=[];const seen=new Set();for(const a of document.querySelectorAll('a[href]')){const u=norm(a.href||a.getAttribute('href'));if(u&&u.startsWith('https://manko.fun/movie-info/')&&!seen.has(u)){seen.add(u);out.push(u)}}return out};let stable=0,last=0;for(let i=0;i<20&&stable<4;i++){window.scrollTo(0,document.body.scrollHeight);await wait(600);const n=collect().length;if(n===last)stable++;else stable=0;last=n}const pages=[];const ps=new Set();for(const a of document.querySelectorAll('a[href]')){const u=norm(a.href||a.getAttribute('href'));if(!u||u.includes('/movie-info/'))continue;try{const A=new URL(startUrl),U=new URL(u);const sameCat=(A.searchParams.get('category')||'')===(U.searchParams.get('category')||'');if(U.origin===A.origin&&sameCat&&U.searchParams.has('page')&&!ps.has(u)){ps.add(u);pages.push(u)}}catch{}}window.scrollTo(0,0);return{url:location.href,movies:collect(),pages}}});return r?.[0]?.result||{url:'',movies:[],pages:[]}}
async function syncCatalogOrder(s){const c=s.crawl;if(!c)return;await postJson('/collector/catalog',{pageUrl:c.startUrl,urls:c.orderedUrls})}
async function enqueueMovies(s,urls){const done=s.crawl.serverDone||[];const doneSet=new Set(done);const busy=new Set([...(s.queue||[]),s.current?.movieUrl].filter(Boolean));let added=0;for(const u of urls){if(!doneSet.has(u)&&!busy.has(u)){s.queue.push(u);busy.add(u);added++}}return added}
async function gotoNextPage(){const s=await getState(),c=s.crawl;if(!c?.active)return;c.pagesPending=[...new Set(c.pagesPending)].sort((a,b)=>pageNo(a)-pageNo(b));while(c.pagesPending.length&&c.pagesVisited.includes(c.pagesPending[0]))c.pagesPending.shift();if(!c.pagesPending.length){c.active=false;c.finishedAt=new Date().toISOString();await setState(s);await syncCatalogOrder(s);if(c.tabId)try{await chrome.tabs.remove(c.tabId)}catch{}processNext();return}const u=c.pagesPending.shift();c.currentPage=u;c.processing=false;await setState(s);try{if(c.tabId)await chrome.tabs.update(c.tabId,{url:u,active:false});else{const t=await chrome.tabs.create({url:u,active:false});c.tabId=t.id;await setState(s)}}catch(e){c.lastError=String(e);await setState(s);setTimeout(gotoNextPage,1000)}}
async function handleCrawlLoaded(tabId){const s=await getState(),c=s.crawl;if(!c?.active||c.tabId!==tabId||c.processing)return;c.processing=true;await setState(s);try{const p=await scrapeCatalog(tabId,c.startUrl);const cur=p.url||c.currentPage;if(!c.pagesVisited.includes(cur))c.pagesVisited.push(cur);for(const u of p.pages||[])if(sameCatalog(c.startUrl,u)&&!c.pagesVisited.includes(u)&&!c.pagesPending.includes(u))c.pagesPending.push(u);const fresh=[];for(const u of p.movies||[]){if(!c.orderedUrls.includes(u)){c.orderedUrls.push(u);fresh.push(u)}}c.pagesScanned=c.pagesVisited.length;c.moviesFound=c.orderedUrls.length;await enqueueMovies(s,fresh);s.totalDiscovered=c.orderedUrls.length;c.processing=false;await setState(s);await syncCatalogOrder(s);processNext();await gotoNextPage()}catch(e){c.lastError=String(e);c.processing=false;if(c.currentPage&&!c.pagesVisited.includes(c.currentPage))c.pagesVisited.push(c.currentPage);await setState(s);gotoNextPage()}}
async function startFullCrawl(startUrl){if(!String(startUrl||'').startsWith('https://manko.fun/'))return{ok:false,error:'Mở trang danh sách Manko trước'};const s=await getState();if(s.crawl?.active)return{ok:false,error:'Crawler đang chạy'};const done=await serverDoneSet();s.mode='stream';s.crawl={active:true,startUrl,pagesPending:[startUrl],pagesVisited:[],orderedUrls:[],serverDone:[...done],pagesScanned:0,moviesFound:0,currentPage:null,tabId:null,processing:false,startedAt:new Date().toISOString(),lastError:null};await setState(s);gotoNextPage();return{ok:true,alreadyStored:done.size}}
async function recover(){const s=await getState();if(s.running&&s.current?.movieUrl){if(!s.queue.includes(s.current.movieUrl))s.queue.unshift(s.current.movieUrl);s.running=false;s.current=null}if(s.crawl?.active){s.crawl.tabId=null;s.crawl.processing=false;if(s.crawl.currentPage&&!s.crawl.pagesVisited.includes(s.crawl.currentPage))s.crawl.pagesPending.unshift(s.crawl.currentPage)}await setState(s);if(s.crawl?.active)gotoNextPage();processNext()}

chrome.tabs.onUpdated.addListener((tabId,change)=>{if(change.status==='complete')handleCrawlLoaded(tabId)});
chrome.tabs.onRemoved.addListener(async tabId=>{const s=await getState();if(s.crawl?.active&&s.crawl.tabId===tabId){s.crawl.tabId=null;s.crawl.processing=false;if(s.crawl.currentPage&&!s.crawl.pagesVisited.includes(s.crawl.currentPage))s.crawl.pagesPending.unshift(s.crawl.currentPage);await setState(s);gotoNextPage()}});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{(async()=>{
 if(msg.type==='START_FULL_CRAWL'){sendResponse(await startFullCrawl(msg.startUrl));return}
 if(msg.type==='RETRY_ERRORS'){const s=await getState();const urls=[...new Set((s.errors||[]).map(x=>x.movieUrl).filter(isManko))];s.errors=[];const busy=new Set([...(s.queue||[]),s.current?.movieUrl].filter(Boolean));for(const u of urls)if(!busy.has(u))s.queue.push(u);await setState(s);processNext();sendResponse({ok:true,added:urls.length});return}
 if(msg.type==='MANKO_PLAYER_FOUND'){const s=await getState(),c=s.current;if(!c)return;c.movieId=msg.movieId||((msg.movieUrl.match(/\/movie-info\/([^/?#]+)/)||[])[1]||'');c.title=msg.title||'';c.poster=msg.poster||'';c.metadata=await enrichManko(c.movieId,msg.title,msg.metadata||{});c.titleVi=c.metadata.titleVi||cleanTitle(msg.title);c.playerUrls=[...new Set((msg.playerUrls||[msg.playerUrl]).filter(Boolean))];c.playerIndex=0;c.streams=[];await setState(s);if(!c.playerUrls.length){sendResponse({ok:false});return finishCurrent(false,{error:'No javplayer embed'})}openNextPlayer();sendResponse({ok:true,players:c.playerUrls.length});return}
 if(msg.type==='JAVPLAYER_RESULT'){const s=await getState(),c=s.current;if(!c)return;if(msg.ok&&msg.streamUrl&&!c.streams.some(x=>x.url===msg.streamUrl))c.streams.push({name:'#'+(c.streams.length+1),url:msg.streamUrl,headers:msg.headers||{Referer:REFERER},playerId:msg.playerId,playerUrl:msg.playerUrl});await setState(s);openNextPlayer();sendResponse({ok:true});return}
 if(msg.type==='GET_STATE'){sendResponse(await getState());return}
 })();return true});
chrome.runtime.onInstalled.addListener(recover);chrome.runtime.onStartup.addListener(recover);recover();
